# LG TV Downstairs
- platform: webostv
  scan_interval: 1
  host: 10.0.0.101
  name: LivingRoom_TV
  turn_on_action: 
    service: mqtt.publish
    data:
      topic: "livingroom/tv"
      payload: "TV"
  customize:
    sources:
      - livetv
      - youtube
      - netflix
      - Plex
      - HDMI1
      - HDMI2

# Spotify
- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret